"""dodat_status_korisnika

Revision ID: 67d4b73dc12e
Revises: caac721204c5
Create Date: 2026-05-27 23:14:17.789137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d4b73dc12e'
down_revision: Union[str, Sequence[str], None] = 'caac721204c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.Enum('active', 'inactive', name='userstatus'), server_default='active', nullable=False))
    op.add_column('users', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deactivated_at')
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
