"""initial migration

Revision ID: d1d4ab232c5c
Revises: 
Create Date: 2026-05-17 15:41:53.715862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d4ab232c5c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    raise RuntimeError(
        "Initial Alembic migration is empty. Replace this placeholder with "
        "the generated op.create_table(...) operations for the initial "
        "schema (including the required 'oglasi' and 'applications' tables), "
        "or regenerate the migration after importing all models into "
        "Alembic target_metadata."
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    raise RuntimeError(
        "Initial Alembic migration is empty. Replace this placeholder with "
        "the matching op.drop_table(...) operations in reverse dependency "
        "order after defining the real upgrade() schema changes."
    )
    # ### end Alembic commands ###
