"""dodani nivoi reputacija i medalje

Revision ID: f36a67ba10b3
Revises: d0bc9e1219bc
Create Date: 2026-06-14 21:19:19.039435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f36a67ba10b3'
down_revision: Union[str, Sequence[str], None] = 'd0bc9e1219bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_reputation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('points_delta', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key', name='uq_forum_reputation_event_key')
    )
    op.create_index(op.f('ix_forum_reputation_events_event_key'), 'forum_reputation_events', ['event_key'], unique=False)
    op.create_index(op.f('ix_forum_reputation_events_user_id'), 'forum_reputation_events', ['user_id'], unique=False)
    op.create_table('forum_user_medals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'medal_code', name='uq_forum_user_medal')
    )
    op.create_index(op.f('ix_forum_user_medals_medal_code'), 'forum_user_medals', ['medal_code'], unique=False)
    op.create_index(op.f('ix_forum_user_medals_user_id'), 'forum_user_medals', ['user_id'], unique=False)
    op.create_table('forum_user_stats',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reputation_points', sa.Integer(), nullable=False),
    sa.Column('topics_started_count', sa.Integer(), nullable=False),
    sa.Column('answers_count', sa.Integer(), nullable=False),
    sa.Column('best_answers_count', sa.Integer(), nullable=False),
    sa.Column('night_topics_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forum_user_stats')
    op.drop_index(op.f('ix_forum_user_medals_user_id'), table_name='forum_user_medals')
    op.drop_index(op.f('ix_forum_user_medals_medal_code'), table_name='forum_user_medals')
    op.drop_table('forum_user_medals')
    op.drop_index(op.f('ix_forum_reputation_events_user_id'), table_name='forum_reputation_events')
    op.drop_index(op.f('ix_forum_reputation_events_event_key'), table_name='forum_reputation_events')
    op.drop_table('forum_reputation_events')
    # ### end Alembic commands ###
